### ISSUE TITLE
Unable to import, Unavailable by ICMP Ping is a dependency but does not exist.

### ISSUE THREAD

**Issue by andrewhughes1988** [Elkropac/zbx-dell-n-series#2]
I was unable to import this template directly into Zabbix 6.4. The error stated the "Dell N-Series: No SNMP data collection depends on trigger Unavailable by ICMP Ping but it does not exist."

I've already updated the template dependency name to "ICMP: Unavailable by ICMP ping" which resolved the issue on my end. Just wanted to leave this here in case anyone else runs across it. I'm not sure if all default instances of Zabbix have appended the ICMP: prefix to that template trigger or not, this may not affect everyone.

**Comment by Elkropac** [comment]
Hi, thanks for the report.

I have removed ICMP items from the template and made it to depend on ICMP template. I will look into it and probably import the items back

**Comment by Elkropac** [comment]
Is it the same as this file? https://github.com/Elkropac/zbx-dell-n-series/blob/devel_6.4/6.4/zbx-dell-n-series.yaml 

I don't have zabbix 6.4 to test

**Comment by Elkropac** [comment]
Thanks for info
